name: User Service Build
run-name: User Service Build

on:
  push:
    branches:
      - main
    paths:
      - 'UserService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # ================= PYTHON BUILD ===================
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install mariadb connector
        working-directory: ./UserService
        run: |
          sudo apt install wget

          wget https://r.mariadb.com/downloads/mariadb_repo_setup

          echo "ad125f01bada12a1ba2f9986a21c59d2cccbe8d584e7f55079ecbeb7f43a4da4  mariadb_repo_setup" | sha256sum -c -

          sudo chmod +x mariadb_repo_setup

          sudo ./mariadb_repo_setup --mariadb-server-version="mariadb-10.6"

          sudo apt install libmariadb3 libmariadb-dev --yes


      - name: Install dependencies
        working-directory: ./UserService/UserAPI
        run: |
          python -m pip install --upgrade pip
          #pip install ruff pythest -> no pytest
          pip install ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
    # - name: Test with pytest
    #     run: |
    #       pytest
